-- =====================================================================
-- SEED: catalogo_etapas y catalogo_materiales
-- Sistema de Seguimiento de Casas
-- Se puede correr las veces que sea necesario para agregar/actualizar
-- filas del catalogo: usa "insert ... on conflict do update" (upsert), NO
-- trunca las tablas. IMPORTANTE: antes se truncaba con "cascade", pero
-- proyecto_etapas y gastos referencian catalogo_etapas(id) por FK, y
-- TRUNCATE ... CASCADE en Postgres tambien trunca esas tablas dependientes
-- (sin importar el on delete de la FK) — eso borro por accidente el avance
-- y los gastos de proyectos reales/demo el 2026-07-29. No volver a usar
-- truncate aqui.
-- =====================================================================

-- Si catalogo_materiales aun no tiene la columna escala_por, agregala:
alter table catalogo_materiales add column if not exists escala_por text not null default 'm2';
-- Si catalogo_etapas aun no tiene la columna es_paralelo, agregala:
alter table catalogo_etapas add column if not exists es_paralelo boolean not null default false;

-- ---------------------------------------------------------------------
-- catalogo_etapas (33 filas, id explicito = orden, para que
-- catalogo_materiales pueda referenciarlas directo mas abajo)
-- es_paralelo = true: la etapa corre en paralelo a la línea secuencial de
-- la obra y no atrasa el resto del proyecto (ventanas, deck, retiro de
-- escombros/limpieza, fosa séptica, conexiones exteriores).
-- ---------------------------------------------------------------------
insert into catalogo_etapas (id, modalidad, orden, nombre, duracion_semanas_est, lead_time_dias_compra, es_paralelo) values
  (1, 'Obra Gruesa Habitable', 1, 'Preparación de terreno', 0.5, 7, false),
  (2, 'Obra Gruesa Habitable', 2, 'Radier', 3, 10, false),
  (3, 'Obra Gruesa Habitable', 3, 'Paneles SIP', 1.5, 15, false),
  (4, 'Obra Gruesa Habitable', 4, 'Techumbre', 1.5, 12, false),
  (5, 'Obra Gruesa Habitable', 5, 'Cielo falso', 0.6, 7, false),
  (6, 'Obra Gruesa Habitable', 6, 'Electricidad', 1, 7, false),
  (7, 'Obra Gruesa Habitable', 7, 'Sanitarios', 1, 7, false),
  (8, 'Obra Gruesa Habitable', 8, 'Volcanita muros', 1, 7, false),
  (9, 'Obra Gruesa Habitable', 9, 'Premarcos', 0.3, 5, false),
  (10, 'Obra Gruesa Habitable', 10, 'Aleros', 1, 7, false),
  (11, 'Obra Gruesa Habitable', 11, 'Revestimiento exterior', 2, 10, false),
  (12, 'Obra Gruesa Habitable', 12, 'Ventanas (subcontrato)', 0.3, 15, true),
  (13, 'Obra Gruesa Habitable', 13, 'Deck (opcional)', 0.6, 7, true),
  (14, 'Obra Gruesa Habitable', 14, 'Retiro de escombros y limpieza', 0.4, 3, true),
  (15, 'Llave en Mano', 15, 'Empaste y preparación cielos/muros', 1.5, 10, false),
  (16, 'Llave en Mano', 16, 'Marcos de puertas', 0.3, 5, false),
  (17, 'Llave en Mano', 17, 'Afinado de piso', 1, 7, false),
  (18, 'Llave en Mano', 18, 'Baños (revestimiento)', 1.5, 10, false),
  (19, 'Llave en Mano', 19, 'Colocación piso vinílico', 0.6, 10, false),
  (20, 'Llave en Mano', 20, 'Instalación porcelanato', 2, 12, false),
  (21, 'Llave en Mano', 21, 'Molduras y guardapolvos', 1, 7, false),
  (22, 'Llave en Mano', 22, 'Baños terminaciones', 0.5, 14, false),
  (23, 'Llave en Mano', 23, 'Puertas interiores y exteriores', 1, 14, false),
  (24, 'Llave en Mano', 24, 'Pinturas', 1, 7, false),
  (25, 'Llave en Mano', 25, 'Remate final interior', 1, 5, false),
  (26, 'Llave en Mano', 26, 'Gasfitería', 0.3, 7, false),
  (27, 'Llave en Mano', 27, 'Muebles cocina y closets', 0.6, 45, false),
  (28, 'Llave en Mano', 28, 'Griferías, lavaplatos y logia', 0.6, 14, false),
  (29, 'Llave en Mano', 29, 'Limpieza interior', 0.6, 3, true),
  (30, 'Llave en Mano', 30, 'Deck exterior', 0.6, 7, true),
  (31, 'Llave en Mano', 31, 'Limpieza ext. y retiro escombros', 0.15, 3, true),
  (32, 'Llave en Mano', 32, 'Fosa séptica', 0.3, 10, true),
  (33, 'Llave en Mano', 33, 'Conexiones luz/agua exteriores', 0.6, 7, true),
  (34, 'Obra Gruesa Habitable', 34, 'Varios', 0, 0, true)
on conflict (id) do update set
  modalidad = excluded.modalidad,
  orden = excluded.orden,
  nombre = excluded.nombre,
  duracion_semanas_est = excluded.duracion_semanas_est,
  lead_time_dias_compra = excluded.lead_time_dias_compra,
  es_paralelo = excluded.es_paralelo;

select setval(pg_get_serial_sequence('catalogo_etapas','id'), (select max(id) from catalogo_etapas));

-- ---------------------------------------------------------------------
-- catalogo_materiales (113 filas)
-- ---------------------------------------------------------------------
insert into catalogo_materiales (etapa_id, material, unidad_default, escala_por) values
  (1, 'Pitilla', 'rollo', 'm2'),
  (1, 'Madera', 'pza', 'm2'),
  (1, 'Estacas', 'un', 'm2'),
  (1, 'Huincha', 'un', 'm2'),
  (1, 'Hilo albañil', 'rollo', 'm2'),
  (1, 'Fierro liso', 'un', 'm2'),
  (1, 'Retroexcavadora (arriendo/día) (opcional)', 'día', 'm2'),
  (1, 'Traslado contenedor', 'gl', 'm2'),
  (1, 'Arriendo baño químico', 'gl', 'm2'),
  (1, 'Maicillo', 'm3', 'm2'),
  (1, 'Estabilizado', 'm3', 'm2'),
  (1, 'Gravilla', 'm3', 'm2'),
  (1, 'Bolón', 'm3', 'm2'),
  (1, 'Manguera', 'un', 'm2'),
  (1, 'Copla', 'un', 'm2'),
  (2, 'Cemento', 'saco', 'm2'),
  (2, 'Cadenas Acma', 'un', 'm2'),
  (2, 'Malla Acma', 'un', 'm2'),
  (2, 'Gravilla', 'm3', 'm2'),
  (2, 'Arena', 'm3', 'm2'),
  (2, 'Tubería PVC 110mm', 'tiras', 'm2'),
  (2, 'Tubería PVC 50mm', 'tiras', 'm2'),
  (2, 'Clavos 3"', 'kg', 'm2'),
  (2, 'Clavos 4"', 'kg', 'm2'),
  (2, 'Puntas', 'un', 'm2'),
  (2, 'Tapas Pino Canteada', 'un', 'm2'),
  (2, 'Alambre', 'kg', 'm2'),
  (2, 'Pino Bruto 2x2', 'pza', 'm2'),
  (2, 'Pino Bruto 1x4', 'pza', 'm2'),
  (2, 'Polietileno negro', 'rollo', 'm2'),
  (3, 'Madera', 'pza', 'm2'),
  (3, 'Membrana hidrófuga', 'rollo', 'm2'),
  (3, 'Caja eléctrica', 'un', 'm2'),
  (3, 'Salidas de caja', 'un', 'm2'),
  (3, 'Panel SIP 90mm', 'un', 'm2'),
  (3, 'Panel SIP 114mm', 'un', 'm2'),
  (3, 'Madera 2x4 cepillado impregnado', 'pza', 'm2'),
  (3, 'Madera 2x3 cepillado impregnado', 'pza', 'm2'),
  (3, 'Conduit', 'tiras', 'm2'),
  (3, 'Perno de anclaje 4"', 'un', 'm2'),
  (3, 'Perno de anclaje 3/8x8"', 'un', 'm2'),
  (3, 'Perno de anclaje 1/2x3 1/4"', 'un', 'm2'),
  (3, 'Tornillo CRS 6-9 x 1 5/8', 'un', 'm2'),
  (3, 'Turbo 6"', 'un', 'm2'),
  (3, 'Turbo 5 1/2"', 'un', 'm2'),
  (3, 'Turbo 4"', 'un', 'm2'),
  (3, 'Turbo 3"', 'un', 'm2'),
  (3, 'Tornillos 3"', 'un', 'm2'),
  (3, 'Perfil metálico cuadrado 100x100x3mm', 'un', 'm2'),
  (3, 'Rectangular 100x50', 'un', 'm2'),
  (3, 'Electrodo Solweld E6011 3/32', 'kg', 'm2'),
  (3, 'Tornillo Chipboard 14 (6.0) x 100/60', 'un', 'm2'),
  (3, 'Tornillo Chipboard 14 (6.0) x 140/72', 'un', 'm2'),
  (3, 'Tornillo Chipboard 14 (6.0) x 160/72', 'un', 'm2'),
  (3, 'Tornillo Chipboard 8 (4.0) x 25', 'un', 'm2'),
  (3, 'Tornillo Chipboard 8 (4.0) x 40', 'un', 'm2'),
  (3, 'Corchetes', 'caja', 'm2'),
  (4, 'Planchas zinc prepintado', 'un', 'm2'),
  (4, 'Cortagoteras', 'tiras', 'm2'),
  (4, 'OSB', 'plancha', 'm2'),
  (4, 'Teja asfáltica', 'caja', 'm2'),
  (4, 'Plancha lisa zinc', 'un', 'm2'),
  (4, 'Plancha 5V Zincalum', 'un', 'm2'),
  (4, 'Perfil C 60', 'un', 'm2'),
  (4, 'Perfil U 60', 'un', 'm2'),
  (4, 'Metalcon Port 40R', 'un', 'm2'),
  (4, 'Perfil C 90', 'un', 'm2'),
  (4, 'Perfil U 90', 'un', 'm2'),
  (4, 'Omega estructural 0,85', 'un', 'm2'),
  (4, 'Clavos 1" (teja asfáltica)', 'kg', 'm2'),
  (4, 'Tubo bajada canaleta 3mt (adicional)', 'un', 'm2'),
  (4, 'Codo canaleta (adicional)', 'un', 'm2'),
  (4, 'Abrazadera tubo (adicional)', 'un', 'm2'),
  (4, 'Tornillo Truss Phillips 8-18 x 1/2', 'un', 'm2'),
  (4, 'Tornillo P.Broca 6-20 x 1', 'un', 'm2'),
  (4, 'Disco Corte Metal Inox 4 1/2"', 'un', 'm2'),
  (4, 'Tapacán 1x8', 'pza', 'm2'),
  (4, 'Cerestain Encina o natural', 'galón', 'm2'),
  (4, 'Membrana hidrófuga', 'rollo', 'm2'),
  (5, 'Volcanita cielo', 'plancha', 'm2'),
  (5, 'Perfiles omega', 'tiras', 'm2'),
  (5, 'Perfiles de borde', 'tiras', 'm2'),
  (5, 'Perfiles perimetrales', 'tiras', 'm2'),
  (5, 'Cornisas poliestireno', 'un', 'm2'),
  (5, 'Cintas de fibra de vidrio', 'rollo', 'm2'),
  (5, 'Madera 1x8 cepillada', 'pza', 'm2'),
  (5, 'Pino Bruto 2x2', 'pza', 'm2'),
  (5, 'Pino Cielo 3/4 x 4', 'pza', 'm2'),
  (5, 'Pino Cielo 1/2 x 4', 'pza', 'm2'),
  (5, 'Pino Cepillado 1x2', 'pza', 'm2'),
  (5, 'Tornillo CRS 6-9 x 1 1/4', 'un', 'm2'),
  (5, 'Aislación fibra de vidrio 90mm', 'rollo', 'm2'),
  (6, 'Curva PVC', 'un', 'm2'),
  (6, 'Cable eléctrico', 'rollo', 'm2'),
  (6, 'Tablero eléctrico', 'un', 'fijo'),
  (6, 'Caja eléctrica', 'un', 'm2'),
  (6, 'Tubería Conduit 20mm', 'tiras', 'm2'),
  (6, 'Salidas de caja', 'un', 'm2'),
  (6, 'Cable Rojo 2,5mm', 'rollo', 'm2'),
  (6, 'Cable Rojo 1,5mm', 'rollo', 'm2'),
  (6, 'Cable Verde 2,5mm', 'rollo', 'm2'),
  (6, 'Cable Verde 1,5mm', 'rollo', 'm2'),
  (6, 'Cable Blanco 2,5mm', 'rollo', 'm2'),
  (6, 'Cable Blanco 1,5mm', 'rollo', 'm2'),
  (6, 'Abrazaderas 20mm', 'un', 'm2'),
  (6, 'Conectores Cónicos Amarillos', 'un', 'm2'),
  (6, 'Cinta Aisladora', 'rollo', 'm2'),
  (6, 'Ferrule 2,5mm', 'un', 'm2'),
  (6, 'Barra Cooper 10mm', 'un', 'm2'),
  (6, 'Conector de Barra', 'un', 'm2'),
  (6, 'Caja Estanco', 'un', 'm2'),
  (6, 'Cámara Eléctricas', 'un', 'm2'),
  (6, 'Tubería conduit 32mm', 'tiras', 'm2'),
  (6, 'Curvas 32mm', 'un', 'm2'),
  (6, 'Barra Partidora Tripolar 7 puestos', 'un', 'm2'),
  (6, 'Borneras de conexión 2,5mm', 'un', 'm2'),
  (6, 'Luz Piloto Riel Din Lexo', 'un', 'm2'),
  (6, 'Interruptor Stanford', 'un', 'm2'),
  (6, 'Barra toma tierra', 'un', 'm2'),
  (6, 'Prensa de Bronce CTT-1 5/8"', 'un', 'm2'),
  (6, 'Interruptor Diferencial 2x25A', 'un', 'm2'),
  (6, 'Interruptor Diferencial 2x40A', 'un', 'm2'),
  (6, 'Interruptor Automático 1x10A', 'un', 'm2'),
  (6, 'Interruptor Automático 1x16A', 'un', 'm2'),
  (6, 'Interruptor Automático 1x32A', 'un', 'm2'),
  (6, 'Barra Repartidora Tetrapolar 125A 7 polos', 'un', 'm2'),
  (6, 'Amarra plástica Negra', 'un', 'm2'),
  (6, 'Vinilit', 'un', 'm2'),
  (6, 'Gas Butano', 'un', 'm2'),
  (6, 'Enchufe macho volante 10A 2P+T', 'un', 'm2'),
  (6, 'Hembra volante 2P+T 10A', 'un', 'm2'),
  (6, 'Caja derivación embutida tabique', 'un', 'm2'),
  (6, 'Capuchón 50mm', 'un', 'm2'),
  (6, 'Cordón eléctrico 3x2,5mm', 'rollo', 'm2'),
  (6, 'Salida caja conduit 32mm', 'un', 'm2'),
  (6, 'Broca metal escalonada 4-32mm', 'un', 'm2'),
  (7, 'Tuberías PPR 25mm', 'tiras', 'm2'),
  (7, 'Codos', 'un', 'm2'),
  (7, 'Llaves de paso', 'un', 'm2'),
  (7, 'Coplas', 'un', 'm2'),
  (7, 'T PPR', 'un', 'm2'),
  (7, 'Codo PPR HI 25mm', 'un', 'm2'),
  (7, 'Codo PPR HE 25mm', 'un', 'm2'),
  (7, 'Codo 50mm', 'un', 'm2'),
  (7, 'Copla 50mm', 'un', 'm2'),
  (7, 'Tapa 50mm', 'un', 'm2'),
  (7, 'Vinilit', 'un', 'm2'),
  (7, 'Espuma', 'un', 'm2'),
  (7, 'Abrazaderas de metal', 'un', 'm2'),
  (7, 'Tapas ciegas', 'un', 'm2'),
  (7, 'Tubo PVC presión 25mm PN12,5', 'tiras', 'm2'),
  (7, 'Tubo PVC presión 32mm PN10', 'tiras', 'm2'),
  (7, 'Tee PVC presión 25mm', 'un', 'm2'),
  (7, 'Terminal PVC presión HE 25mm x 3/4"', 'un', 'm2'),
  (7, 'Terminal PVC presión HI 25mm x 3/4"', 'un', 'm2'),
  (7, 'Terminal PVC presión HE 32mm x 1"', 'un', 'm2'),
  (7, 'Terminal PVC presión HI 32mm x 1"', 'un', 'm2'),
  (7, 'Unión americana PVC presión 32mm', 'un', 'm2'),
  (7, 'Unión americana PVC presión 25mm', 'un', 'm2'),
  (7, 'Codo PVC presión 32mm x 90°', 'un', 'm2'),
  (7, 'Codo PVC presión 32mm x 45°', 'un', 'm2'),
  (7, 'Teflón gas 3/4"', 'rollo', 'm2'),
  (7, 'Terminal PPR 32mm x 3/4 HE', 'un', 'm2'),
  (7, 'Cañería plana virgen 1/2"', 'ml', 'm2'),
  (7, 'Tapa PVC 110mm', 'un', 'm2'),
  (7, 'Tapa tornillo PPR HE 1/2"', 'un', 'm2'),
  (7, 'Codo PPR 25mm x 45°', 'un', 'm2'),
  (7, 'Gas Butano', 'un', 'm2'),
  (7, 'Soplete', 'un', 'm2'),
  (8, 'Volcanita', 'plancha', 'm2'),
  (8, 'Internit', 'plancha', 'm2'),
  (8, 'Terciado ranurado', 'plancha', 'm2'),
  (8, 'Tornillo CRS 6-9 x 1 1/4', 'un', 'm2'),
  (8, 'Cintas de fibra de vidrio muros', 'rollo', 'm2'),
  (8, 'Maskintape', 'rollo', 'm2'),
  (9, 'Pino 1x8', 'pza', 'm2'),
  (9, 'Barniz', 'galón', 'm2'),
  (9, 'Pintura Premarcos', 'galón', 'm2'),
  (9, 'Tornillos Zincado 2"', 'un', 'm2'),
  (10, 'Pino bruto 1x2', 'pza', 'm2'),
  (10, 'Pino Cepillado 1x8', 'pza', 'm2'),
  (10, 'Pintura Cerestain', 'galón', 'm2'),
  (10, 'Puntas', 'bolsas', 'm2'),
  (10, 'Pino forro machihembrado', 'un', 'm2'),
  (10, 'Barniz', 'galón', 'm2'),
  (10, 'Tornillo CRS 8-9 x 2 1/2', 'un', 'm2'),
  (10, 'Tornillo CRS 8-9 x 3', 'un', 'm2'),
  (11, 'Siding fibrocemento', 'un', 'm2'),
  (11, 'Madera listones 1x2 cepillado impregnado', 'pza', 'm2'),
  (11, 'Clavos Hilti', 'un', 'm2'),
  (11, 'Pintura Siding', 'galón', 'm2'),
  (11, 'Pintura Perfiles metálicos', 'galón', 'm2'),
  (11, 'Tornillos 1 1/4', 'un', 'm2'),
  (11, 'Perfil J Blanco siding fibrocemento', 'un', 'm2'),
  (11, 'Perfil cortagotera base siding', 'un', 'm2'),
  (11, 'Perfil cortago. ventana siding', 'un', 'm2'),
  (11, 'Perfil esquinero', 'un', 'm2'),
  (12, 'Ventanas PVC termopanel', 'gl', 'm2'),
  (13, 'Turbo 4"', 'un', 'm2'),
  (13, 'Clavos 3"', 'kg', 'm2'),
  (13, 'Rollizo 4"-5"', 'un', 'm2'),
  (13, 'Rollizo 5"-6"', 'un', 'm2'),
  (13, 'Pino 2x6 impregnado bruto', 'un', 'm2'),
  (13, 'Pino 2x4 impregnado bruto', 'un', 'm2'),
  (13, 'Tabla Pino Impregnado 1 1/2 x 4', 'un', 'm2'),
  (13, 'Tornillos Zincado 3"', 'un', 'm2'),
  (14, 'Flete/contenedor', 'gl', 'm2'),
  (14, 'Insumos de limpieza', 'gl', 'm2'),
  (15, 'Macilla base', 'saco', 'm2'),
  (15, 'Pasta muro', 'saco', 'm2'),
  (15, 'Látex', 'galón', 'm2'),
  (15, 'Huincha malla', 'rollo', 'm2'),
  (15, 'Yeso', 'saco', 'm2'),
  (15, 'Lija', 'un', 'm2'),
  (15, 'Cornizas', 'un', 'm2'),
  (15, 'Pegamento cornizas', 'un', 'm2'),
  (15, 'Adhesivo montante', 'un', 'm2'),
  (16, 'Marcos de puerta de pino interiores', 'un', 'm2'),
  (16, 'Tornillos 2"', 'caja', 'm2'),
  (17, 'Puente adherente', 'un', 'm2'),
  (17, 'Sacos afinado piso', 'saco', 'm2'),
  (17, 'Mortero piso', 'saco', 'm2'),
  (18, 'Revestimiento piso', 'm2', 'banos'),
  (18, 'Revestimiento muro', 'm2', 'banos'),
  (19, 'Piso vinílico', 'm2', 'm2'),
  (20, 'Porcelanato', 'm2', 'm2'),
  (20, 'Pegamento', 'saco', 'm2'),
  (20, 'Separadores', 'bolsa', 'm2'),
  (20, 'Plásticos protección', 'rollo', 'm2'),
  (20, 'Fragües', 'kg', 'm2'),
  (20, 'Discos', 'un', 'm2'),
  (20, 'Esponja fraguadora', 'un', 'm2'),
  (20, 'Rodillera acolchada', 'un', 'm2'),
  (20, 'Clips niveladores', 'un', 'm2'),
  (21, 'Moldura pecho paloma', 'ml', 'm2'),
  (21, 'Guardapolvos', 'ml', 'm2'),
  (21, 'Junquillos', 'ml', 'm2'),
  (21, 'Pegamento', 'un', 'm2'),
  (21, 'Cubrejuntas', 'ml', 'm2'),
  (21, 'Fijaciones', 'caja', 'm2'),
  (21, 'Pilastras', 'un', 'm2'),
  (22, 'Artefactos sanitarios', 'un', 'banos'),
  (22, 'Grifería', 'un', 'banos'),
  (22, 'Accesorios de baño', 'un', 'banos'),
  (22, 'Shower/receptáculo', 'un', 'banos'),
  (22, 'Silicona Transparente', 'un', 'banos'),
  (22, 'Espejo', 'un', 'banos'),
  (22, 'Mueble de baño (vanitorio)', 'un', 'banos'),
  (22, 'Cubierta Vanitorio', 'un', 'banos'),
  (22, 'Mampara de baño', 'un', 'banos'),
  (22, 'Escuadra estabilizadora mampara', 'un', 'banos'),
  (22, 'Barra estabilizadora mampara', 'un', 'banos'),
  (22, 'Desagüe lavamanos', 'un', 'banos'),
  (22, 'Desagüe ducha', 'un', 'banos'),
  (22, 'Sifón lavamanos', 'un', 'banos'),
  (22, 'Porta papel', 'un', 'banos'),
  (22, 'Percha toalla', 'un', 'banos'),
  (22, 'Barra toalla', 'un', 'banos'),
  (22, 'Ácido Muriático', 'un', 'banos'),
  (22, 'Ventilación Aluminio 15x15', 'un', 'banos'),
  (22, 'Kit llave angular y flexible 1/2 x 15/16"', 'un', 'banos'),
  (22, 'Broca paleta', 'un', 'banos'),
  (22, 'Puntas', 'un', 'banos'),
  (22, 'Llave punta corona', 'un', 'banos'),
  (22, 'Broca 45mm', 'un', 'banos'),
  (23, 'Puerta Exterior', 'un', 'm2'),
  (23, 'Puerta Interior', 'un', 'm2'),
  (23, 'Cerradura baños', 'un', 'm2'),
  (23, 'Topes de puertas', 'un', 'm2'),
  (23, 'Cerradura puerta exterior', 'un', 'm2'),
  (23, 'Cerradura dormitorios', 'un', 'm2'),
  (23, 'Bisagra 3 1/2 x 3 1/2', 'un', 'm2'),
  (23, 'Marcos de puerta interiores', 'un', 'm2'),
  (23, 'Marcos de lenga de puerta exteriores', 'un', 'm2'),
  (23, 'Endolados de lenga', 'un', 'm2'),
  (23, 'Formón', 'un', 'm2'),
  (23, 'Sierra copa madera', 'un', 'm2'),
  (23, 'Bocallave', 'un', 'm2'),
  (23, 'Manillón', 'un', 'm2'),
  (24, 'Esmalte al agua', 'galón', 'm2'),
  (24, 'Brocha', 'un', 'm2'),
  (24, 'Rodillo', 'un', 'm2'),
  (24, 'Silicona pintable', 'un', 'm2'),
  (24, 'Joint', 'saco', 'm2'),
  (24, 'Cinta', 'rollo', 'm2'),
  (25, 'Fragüe', 'kg', 'm2'),
  (25, 'Tapas ciegas', 'un', 'm2'),
  (25, 'Tornillos', 'caja', 'm2'),
  (26, 'Cobre', 'ml', 'm2'),
  (26, 'Calefón', 'un', 'fijo'),
  (26, 'Caseta', 'un', 'fijo'),
  (27, 'Muebles de cocina', 'gl', 'm2'),
  (27, 'Closets', 'gl', 'm2'),
  (28, 'Horno', 'un', 'fijo'),
  (28, 'Encimera', 'un', 'fijo'),
  (28, 'Campana', 'un', 'fijo'),
  (28, 'Lavaplatos', 'un', 'fijo'),
  (29, 'Insumos de limpieza', 'gl', 'm2'),
  (30, 'Madera deck', 'm2', 'm2'),
  (30, 'Tornillo Chipboard 14 (6.0) x 100/60', 'un', 'm2'),
  (30, 'Turbo 4"', 'un', 'm2'),
  (30, 'Clavos 3"', 'kg', 'm2'),
  (30, 'Rollizo 4"-5"', 'un', 'm2'),
  (30, 'Rollizo 5"-6"', 'un', 'm2'),
  (30, 'Pino 2x6 impregnado bruto', 'un', 'm2'),
  (30, 'Pino 2x4 impregnado bruto', 'un', 'm2'),
  (30, 'Tabla Pino Impregnado 1 1/2 x 4', 'un', 'm2'),
  (30, 'Tornillos Zincado 3"', 'un', 'm2'),
  (31, 'Flete/contenedor', 'gl', 'm2'),
  (32, 'Fosa séptica prefabricada', 'un', 'fijo'),
  (32, 'Excavación', 'm3', 'm2'),
  (32, 'Tubería PVC 110mm', 'ml', 'm2'),
  (33, 'Materiales de conexión', 'gl', 'm2'),
  (2, 'Poliuretano', 'un', 'm2'),
  (4, 'Poliuretano', 'un', 'm2'),
  (12, 'Poliuretano', 'un', 'm2'),
  (22, 'Sello acrílico blanco 300 ml', 'un', 'banos'),
  (5, 'Adhesivo montaje', 'un', 'm2'),
  (5, 'Tornillo autoperforante', 'un', 'm2'),
  (19, 'Adhesivo contacto 1 lt', 'un', 'm2'),
  (34, 'Otros', 'un', 'm2')
on conflict (etapa_id, material) do update set
  unidad_default = excluded.unidad_default,
  escala_por = excluded.escala_por;

select setval(pg_get_serial_sequence('catalogo_materiales','id'), (select max(id) from catalogo_materiales));
